name: csdn

on:
  schedule:
    - cron: "*/20 * * * *"
  push:
    branches:
      - master

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: node
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: run script
        run: |
          cd JSscripts
          npm install
          node csdn.js